// prisma/seed.ts
// Auto-generated by scripts/merge-seeds.js — Do not edit manually
// Edit files in prisma/seeds/ directory instead

import { PrismaClient } from '@prisma/client';
import { seedSelectOptions } from './seeds/select-options.seed';

const prisma = new PrismaClient();

async function main() {
  console.log('🚀 Starting seed...');

  await seedSelectOptions(prisma);

  console.log('✅ Seed completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
